package io.github.zenhelix.github.client.http.api.securityadvisory

public interface GithubSecurityAdvisoriesCoroutineApi : GithubSecurityAdvisoriesGlobalCoroutineApi, GithubSecurityAdvisoriesRepositoryCoroutineApi

public interface GithubSecurityAdvisoriesGlobalCoroutineApi {
}

public interface GithubSecurityAdvisoriesRepositoryCoroutineApi {
}